[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_PRODUCTION_BRANCH = "main"
  NODE_VERSION = "20.11.0"

[functions]
  node_bundler = "esbuild"

  [functions."lfdr-qrng"]
  cache = false
  
[[headers]]
  for = "/.netlify/functions/lfdr-qrng"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"
