[build]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_PRODUCTION_BRANCH = "main"

[context.branch-deploy]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"

[context.deploy-preview]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"
