#!/usr/bin/env bash
# BEGIN build_all.sh
set -euo pipefail

# This script:
# - Builds every experiment under experiments/* automatically
# - Copies each result into _site/<experiment-name>
# - Generates an index page and SPA redirects if a marker file named "SPA" exists

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLISH_DIR="${ROOT_DIR}/_site"
EXP_DIR="${ROOT_DIR}/experiments"

# clean publish dir
rm -rf "${PUBLISH_DIR}"
mkdir -p "${PUBLISH_DIR}"

if [ ! -d "${EXP_DIR}" ]; then
  echo "No experiments/ directory found. Create experiments/* folders."
  exit 1
fi

REDIRECTS_TMP="$(mktemp)"
INDEX_LIST=""

# helper: copy built output or public files
copy_output () {
  local src="$1" dest="$2"
  mkdir -p "${dest}"

  if [ -d "${src}/dist" ]; then
    cp -R "${src}/dist/." "${dest}/"
    return 0
  fi

  if [ -d "${src}/build" ]; then
    cp -R "${src}/build/." "${dest}/"
    return 0
  fi

  if [ -d "${src}/public" ]; then
    cp -R "${src}/public/." "${dest}/"
    return 0
  fi

  # fallback: copy everything (good for already-built static folders)
  shopt -s dotglob
  cp -R "${src}/." "${dest}/"
  shopt -u dotglob
}

# loop through experiments/* subfolders
shopt -s nullglob
for exp_path in "${EXP_DIR}"/*; do
  [ -d "${exp_path}" ] || continue
  exp_name="$(basename "${exp_path}")"
  echo "=== Building experiment: ${exp_name} ==="

  # build if package.json + build script exist
  if [ -f "${exp_path}/package.json" ]; then
    if grep -q '"build"' "${exp_path}/package.json"; then
      echo "Running npm ci && npm run build in ${exp_name}"
      ( cd "${exp_path}" && npm ci && npm run build )
    else
      echo "No \"build\" script in ${exp_name}/package.json; will copy files as-is."
    fi
  fi

  # copy output into _site/<exp_name>
  copy_output "${exp_path}" "${PUBLISH_DIR}/${exp_name}"

  # mark SPA if a file named SPA exists
  if [ -f "${exp_path}/SPA" ]; then
    echo "/${exp_name}/*   /${exp_name}/index.html   200" >> "${REDIRECTS_TMP}"
  fi

  # add to index list if it has an index.html
  if [ -f "${PUBLISH_DIR}/${exp_name}/index.html" ]; then
    INDEX_LIST="${INDEX_LIST}<li><a href=\"/${exp_name}/\">${exp_name}</a></li>"
  else
    INDEX_LIST="${INDEX_LIST}<li>${exp_name} (no index.html)</li>"
  fi
done
shopt -u nullglob

# write _redirects if we created any SPA rules
if [ -s "${REDIRECTS_TMP}" ]; then
  mv "${REDIRECTS_TMP}" "${PUBLISH_DIR}/_redirects"
else
  rm -f "${REDIRECTS_TMP}"
fi

# simple index page
cat > "${PUBLISH_DIR}/index.html" <<HTML
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Experiments</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; }
    h1 { margin-bottom: 0.5rem; }
    .muted { color: #666; margin-bottom: 1.5rem; }
    ul { line-height: 1.9; }
    a { text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>Experiments</h1>
  <div class="muted">Auto-generated by scripts/build_all.sh</div>
  <ul>
    ${INDEX_LIST}
  </ul>
</body>
</html>
HTML

echo "Build complete. Publish dir: ${PUBLISH_DIR}"
# END build_all.sh
